kind: Service
apiVersion: v1
metadata:
  name: devProj
  labels:
    app: devProj
spec:
  selector:
    app: devProj
  ports:
  - port: 8080
    targetPort: 80
    nodePort: 31200
  type: LoadBalancer
